### ISSUE TITLE
Updating and cleaning up newly added tech guides

### ISSUE THREAD

**Issue by Niyousha99** [techstartucalgary/Docs#18]
- [x] Move out the React content from the web devs guide to the React guide and reference it there.
- [x] Address all the "WIP" points in the git guide
- [x] Beef up the React guide to include react native and remove the WIP note at the top
- [x] Rename "GraphQL" guide to "API" gude
- [x] Fix broken links in “Stall Fest” guide

**Comment by Anidion** [comment]
@Anidion will be working on the WIP points in the Git guide
