### ISSUE TITLE
Add Guides to Docs

### ISSUE THREAD

**Issue by Niyousha99** [techstartucalgary/Docs#2]
All current guides can be found [here ](https://techstartucalgary.com/resources), in addition to the [git good slides](https://docs.google.com/presentation/d/1VirWHkI8QHIFB2E71R-vqGcnvhAHgFaG7yQ2FHZ677w/edit?usp=drive_web&ouid=116958691402016136811) from our latest workshop.

**Comment by Niyousha99** [comment]
Follow-up: https://github.com/techstartucalgary/tsu-website/issues/397

**Comment by kamadorueda** [comment]
I'm going to close this one in favor of more granular issues, to track progress better
