### ISSUE TITLE
Add details for demo nights

### ISSUE THREAD

**Issue by Niyousha99** [techstartucalgary/Docs#23]
Update demos section with final dates, itineraries, and expectation (should be approved by project support team and presidents)

**Comment by Niyousha99** [comment]
Include:

- A little context on the purpose of demo nights in preparation for the final showcase (format and expectations)
- Time limit: 15 minutes
- Suggested talking points and questions to address in the demos
- Technical requirements for setup and demoing
- Pre-work / milestones that should be complete by each particular demo night
- Dates and presentation order for each demo night
- (Pizza afterwards as a reward?)

**Comment by Anidion** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Complete pitch night docs](https://trello.com/c/sFMxW4vn/23-complete-pitch-night-docs)
